# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Build
      run: GOOS=linux GOARCH=${ARCH} CGO_ENABLED=0 go build -o /usr/local/bin/goup

    - name: Test
      run: go test -v ./...
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: /usr/local/bin/goup
          
